theme: jekyll-theme-minimal
title: "Latent Diffusion Local Aging (LDLA): Locally Controlled Face Aging with Latent Diffusion Models"
description: A diffusion-based model that offers greater control over the zones of the face by using ethnicity-specific skin atlases.